### ISSUE TITLE
where to set staging port for web admin

### ISSUE THREAD

**Issue by FeynmanDNA** [nusdbsystem/singa-auto#11]
Is the current ncrs.d2 for the Old Rafiki web admin staged/deployed according the `dev` branch? If so, then how is the web admin port being set during deployment?

accroding to the nusDbsystem repo dev branch:
https://github.com/nusdbsystem/rafiki/blob/15df6a31363fe27c7057621d610bd037cc6c22bd/.env.sh#L31
 and
https://github.com/nusdbsystem/rafiki/blob/d5298f6f64a9859e68db55312e35461f0bb88459/web/app.js#L24

the web admin port is set up 3001, so i am wondering how is the current old Rafiki on ncrs on port 30001
http://ncrs.d2.comp.nus.edu.sg:30001/
![image](https://user-images.githubusercontent.com/26617036/76136720-b7d44680-606f-11ea-8513-e1ac2c5a400c.png)

**Comment by FeynmanDNA** [comment]
There are also multiple sources of potential conflict to set the port number for web admin:

1. https://github.com/nusdbsystem/rafiki/blob/15df6a31363fe27c7057621d610bd037cc6c22bd/dockerfiles/web_admin.Dockerfile#L38

the dockerfile for PORT is exposing 3001

2. https://github.com/nusdbsystem/rafiki/blob/d5298f6f64a9859e68db55312e35461f0bb88459/scripts/start_web_admin.sh#L29

the start web admin script is hardcoding the port number again

**Comment by chrishkchris** [comment]
Is it because the port was set in the code before deployment? 
1. he `git clone` the Rafiki repo, and `git checkout dev`
2. he changed the port in the code 
`rafiki/.env.sh line31: export WEB_ADMIN_EXT_PORT=30001`
`rafiki/web/app.js line 24: const port=30001`
`rafiki/dockerfiles/web_admin.Dockerfile line 38: EXPOSE 30001`
`rafiki/scripts/start_web_admin.sh line 29:  -p $WEB_ADMIN_EXT_PORT:30001 \`
3.  run `bash scripts/start.sh` to start the deployment process
I think the Rafiki is not automatically deployed from GitHub so he can change the port after git clone 

@naili-xing If not true, please correct me. Thanks!

**Comment by chrishkchris** [comment]
@FeynmanDNA I agree that the hardcoding might be a potential problem

**Comment by chrishkchris** [comment]
I guess this issue is also related to #7 , if yes, maybe can fix at the same time
