### ISSUE TITLE
Remvoe empty folders

### ISSUE THREAD

**Issue by nudles** [nusdbsystem/singa-auto#112]
There empty folders tracked by git, including data/ params/ logs/ db/.
They should be deleted.

**Comment by naili-xing** [comment]
The empty folder will be mount into container no matter in production & dev environments, if we move them. we had to create them manually when deploy the project.

**Comment by nudles** [comment]
why do we need to mount empty folders?

**Comment by naili-xing** [comment]
Because we don's seperate the file system & computation system and we fix the folder path at environment. Each container will store data to the same path. 
currently, we mount empty folder into container, and container will generate the log, store data, save params, save db etc. Since we use nfs, those folder can be shared by all containers. and the path is fixed, folder name is also fixed.

**Comment by nudles** [comment]
think about how a normal lib/software is installed from the users' perspective.
it's seldom to install a lib via git clone.
the common way is apt install or pip install, which should install the components and run scripts to create the necessary folders.

Ref:  https://setuptools.readthedocs.io/en/latest/setuptools.html#developer-s-guide    **entry_points**

**Comment by naili-xing** [comment]
Solved in https://github.com/nusdbsystem/singa-auto/commit/6a662f89f65f8f16b8a92acc57ea4cbb55555530
